### ISSUE TITLE
Catsuit features

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#122]
Add notes for features here

**Comment by Versh** [comment]
To be honest I have some doubt about it:
Is a device and also a restrictive one for sure... 
But I don't see this scandalous as the other

A Chastity belt speak for itself, a Gag also..

But a catsuit in rubber/leather... Is like watching "underworld" (Gods what a shitty movie)

Anyway:

A catsuit is someting really deviously in a way, but not much on the other.

You're "locked away" from your body, but you could feel the pressure of an hand on you with the relative actions...

Personally I consider the Catsuit an "inconveniance" in the DD optic...

If you wear one your devices are UNDER it, so you couldn't remove any of them (is like the Yoke tricks when you ask help and you get the lock even more secured)

So the Catsuit should be an high level item that in fact make you problematic reach the other locks...

Said so: Other Effect

In fact there's two type of catsuit
The Rigid and the normal, we have already the Restrictive corset (that could be weared under the catsuit) SO i prefer to ignore the "restictive catsuit" and move the freatures of it in the Restictive Corset.

Normal Catsuit:
-A long wear period of a catsuit (especially in rubber/leather) provide a lot of inconvenience, but most of it are irrilevant in Skyrim and could be emulated with a generic "stamina regen -20%"

-You couldn't unlock any device under the catsuit, because the locks are out of your reach

-When asking help to remove the "Infamous helper" could simply unlock the Zip and make you exposed (that will require a alternate mesh of a catsuit with the zip open... I hope that it isn't a problem), If opened and wearing a chastity belt, you're still "safe".
Having an Open Catsuit doesn't allow you to manipulate any locks (also from the belt, in any case you couldn't physically remove it), is a "more unconfortable" variable, also in reality I really discurage to ride an horse with a zip open on your skin

-I think that should have the "clothingbody" keywork, because It is a clothing...

-We could consider also a "damaging event" on the catsuit (because is the most exposed device) that could make easier to remove it, like been hit when the player didn't wear an armor over it...


Restictive Catsuit (Suggestion: move to Restrictive corset)
Is a catsuit that makes the movement more rigid, could be useful for make the "Struggle option" less efficient
Also could debuff melee damage and prevent/debuff sneaking
