### ISSUE TITLE
Mitten features

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#124]
Mittens are gloves type items with a few features:

1) Player has a high chance to drop a key when attempting to unlock something (80%+ chance to drop key)  Key is flung in a random direction, player has to chase it down

2) Player cannot wield weapons, shields, or spells.  Unarmed attacks only

3) Item can be converted from regular gloves using a 'mitten' item.  Can be converted back once removed

To be done when koffii gets around to it (?)

**Comment by Versh** [comment]
I suggest a "more restrictive type" and a "lesser restrictive" (that have an identical mesh.. how cares)
The general idea about a restrictive gloves is about to blame a slave because he/she cannot perform a particular task well, said so, my suggestion:

Lesser Type:
Gloves like that usually have a unique space for all the finger (except the inch), it make things hard to do, but not impossible
General effect:
-Malus to lockpick
-Chance to drop key/lockpick
-Chance to drop weapon when hitting

Special:
-Eventually they could have also a metal ring for tied the hands togheter... that could be considered a variant of the armbinder that could be activate in different way (like calling a modevent)

High type:
Gloves like that generally have individual finger slot and one... I don't know the word... splint? along the fingers that makes hard/impossible to flex them, you CAN hold little items bewteen the fingers, but you couldn't use the inch

General Effect:
-No lockpick
-High chance to drop keys
-Couldn't use weapon/shield
-malus to mana cost (+20% or 30%)
-couldn't use a forge/alchemy table/cook station/enchantment table/etc

Special:
-I know that make a new animation for the punch as slap is too much, but I was thinking: only change the hitting unarmed sound to a slap?

Personally I don't think that this should avoid to cast magic... The "magical" malus is already on some item, and other if you cast a spel they start to vibrate.

It could be a variable, like:
Item restrictive for Everyone, Most restrictive for warrior/Mage/thief

For example, a Warrior or a Mage dindn't care much about a Slave boot... For a thief instead they're a pain in the ass (malus to stealth)

Before thing about other features let me know about the idea about different gloves and restrictive about who (that are more or less, those that Aelie already wrote)

**Comment by TheKimy** [comment]
Bondage Mittens have become available, so we can go ahead with this: http://www.loverslab.com/files/file/2819-the-duders-grab-bag-of-fetish-items-wip/

**Comment by TheKimy** [comment]
Bondage Mittens added. Done.
