### ISSUE TITLE
Swap harness mesh for collar included mesh

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#142]

**Comment by Coopervane** [comment]
Collar included? You do realize that's never going to work (even if, and that a big if, it could ever be made to look alright with other collars, it could not never work with the harness collar which is also a collar we've got, there will be terrible Z-Fighting)?

It's not a collar that needs adding, that will be nothing but pain and problems, it's some kind of shoulder-strap. That's the only thing that has a chance of working, a build-in collar never will.

**Comment by Aelie1** [comment]
always looked fine for me ~_~

**Comment by Coopervane** [comment]
1) No it didn't, i've seen enough screenies from LADL and early DDx to know it never did look good on CBBE either (it wasen't just UNPB that had the problem). And it still looks bad today.

2) Z-Fighting is what happens when two identical meshes are placed ontop of eachother, the textures will fight over which one gets to render making for this very noticable flickering zigzag pattern across the surface. And this is precisely what's going to happen when you wear a harness with attached collar, and then some mod places the loose harness-collar on you. Same mesh, same place, Z-fighting.

Number 2 especially means that we've not fixed anything, just broken another item combo (along with introducing clipping issues with every collar and the harness).


Let's fix this right.

**Comment by Aelie1** [comment]
it looked fine, i remember even taking note of the fact that it worked
fine.   i dont know about UNP though.

the solution i see here is to make the collar version slightly larger or
smaller so they dont clip.

http://imgur.com/a/ju9gE

**Comment by Coopervane** [comment]
It doesen't "look fine" when nobody else can reproduce this. You had me test this with the CBBE body way back, remember? And it didn't look fine, there was obvious clipping that you weren't seeing in your game, remember?

Well that's how it looks on every install but yours. I have no idea what you've got installed, or what you've tweaked around with that makes it look different on your end, but nobody else is seeing it.
How many months ago did LADL first come out? In all that time, every single screenshot i've seen of the harnesses, every single comment i've read about it have all confirmed the clipping with other collars. This is not a problem with my install Aelie, it's a problem with yours, you are seeing results that nobody else can replicate, you are the fluke here, not the exemplar.

For everyone else, stuff's busted. Here, i'll grab some shots off of Deviant Art showing it (and this is plainly the CBBE body):

http://angryangel81.deviantart.com/art/Deviously-Cursed-Loot-11-491939035
http://angryangel81.deviantart.com/art/Deviously-Cursed-Loot-10-491938768

**Comment by Aelie1** [comment]
"excuse for the clipping, i have made a own unique version of the CBBE body
which works good with the nipple rings, but conflicts the harness  .....
Nihals CBBE..."

it may be cbbe but its not vanilla cbbe.  i am sorry that people cant
listen to "dont use body slide if you dont want clipping", but its not my
fault

**Comment by Coopervane** [comment]
Doesen't matter Aelie, i tested it with the standard body and saw the exact same thing (and this was a while ago so it was with the version Zad actually made the assets for), and, Bodyslide doesen't really change the neck as that's part of the head-mesh, not the body (the only difference that ever existed on the CBBE/UNPB harness collars was the slope of the connecting ring, since the two bodies have rather different bust sizes. The actual collar part of it is the same as both bodies use the same head and neck).

Again, you are the only person who doesen't see it, i don't know if it's animations you have installed, edits you've made via ECE or RM, or what it is, but i have not seen anyone repoduce your results.

Sorry, but i am going to fight you on this, i'm not cool with changing the harness to something that seems to work on your PC and yours only. It doesen't work on mine, and it hasen't worked on anyone elses as far as i can tell. Go dig around in the LADL thread if you want, people posted about the clipping there too.

This is not a good change, and it wasen't the last time you did it either. Kof's got a working prototype for something that could actually fix this, we should be looking at that.

**Comment by Aelie1** [comment]
like i said above, we would need to alter the harness slightly to make it
work better (making the collar tighter should alleviate most of the issues,
probably!)
