### ISSUE TITLE
map/compass access while blindfolded

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#29]
i can understand blocking fast travel, but blocking the map altogether makes the game basically unplayable unless you somehow have memorized every single foot of the game.

also the compass disable seems to be clashing with a number of other extremely popular mods.  i'm not sure theres a good way to disable it especially with other mods altering/replacing the compass entirely

**Comment by Versh** [comment]
Uhm..Opinion: I disagree, I prefer the Compass/Map out
The real problem is: The sign system in Skyrim is a bit Shitty (only in cross street).
I don't use the fast travel and I can easily find the way home from every road... and also it add some risk the fact that you could be oriented in the wrong direction.

Why simply a dialog to ask direction?
You find Mai'q / a friendly Npc and you ask direction, and the compass reappear for 30 seconds (until you lost orientation again) [A magic effect that made exception to the check to hide the Compass]

Blindfold are a high restrictive item much underestimated, because we all go to thrid person and 'How cares?' But tecnically with a blindfold you fight -VERY- bad (except that you're some sort of ninja/mook/shaolin), you DONT run, you smash you face everywhere, you don't read sign, you dont jump, you dont see the smoke from the village etc. etc. ...

**Comment by MinLL** [comment]
This ties in with #125. Might want to start doing that in 2.9.1, instead of 2.9.2.

**Comment by TheKimy** [comment]
I have no clear opinion on that. Personally I think the blindfold works as intended. It's supposed to be harsh, but I can see it can be brutal in certain situations when your supposed to go somewhere with an inescapable blindfold. I use these only in controlled situations for that reason, but not sure about other mods.

**Comment by MinLL** [comment]
I don't have a problem with the existing functionality either - it is working as intended. At the time this issue was created, there was a lot of demand for the feature. There doesn't seem to be as such, anymore.

**Comment by TheKimy** [comment]
All right, let's close that one, then.
