### ISSUE TITLE
Yoke Features & Events

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#50]
Basic restraint functionality. 
Integration with Animation Filter (Pending ZapExperimental).
Various events.

More suggestions wanted.

**Comment by Versh** [comment]
Uhmm.. I agree about  Yoke == Armbinder
But the Yoke isn't only a Devious Device, is was also a punisment for criminal.

So could be useful some event related to that... I don't know, a guard whipping event? An event that someone throw to you something (old fruit?) ?

Wearing a Yoke, like an armbinder make you fully helpless (you can only do an head hit or a very clumsy punch, mabye a kick, if you have a good balance), also every hit to the Yoke is like getting hit to the troath, So I think that should focus on the Criminal Punishment/Helpless status

The guard could excange you for a prisioner and put you in Exposition? Like in the cities we decide some spot where the player get exposed in a Zaz Object animation and skip some hours (auto advance)

Also It could be a "Jail Simplified way", a guard think that you're a prisioner escaping and put you in jail with a fee of 100? With all the event of the case (Thane excuse, Persuasion, Etc)

**Comment by Aelie1** [comment]
After some discussions, here is how yokes will be implemented in 2.9.0:

Yokes are very similar to armbinders in many respects

When clicking on an unworn yoke, the player will get a dialog with these options:
-Put on
-Manipulate locks
-Put away

These options work the same as they do for armbinders.

Once a player puts on a yoke, they play the yoke offset animation and have the same restrictions as when they wear an armbinder

When a player tabs or interacts with a worn yoke, they get the following menu:
-Take it off
-Struggle
-Endure your bonds

--Take it off:
When taking it off, if the player had manipulated the locks before hand, then the player can attempt to remove the item. A struggle sequence happens, and based on a random chance (33%?) is able to remove the yoke.  (This is because even with the locks unengaged, it is very difficult to get the locks out of their holes)

Otherwise, a screen informs them of the futility of this attempt

--Struggle:
If the player has the key in their inventory, they can struggle to insert the key into the locks.  This works the same way as armbinder struggling:  5 minimum struggles, then an increasing chance to succeed on each subsequent attempt.  When they succeed, the yoke is unlocked and then functions the same as if the player had manipulated the locks (must struggle to attempt to remove it as above)


--NPC interaction
If the player has the key in their inventory, any npc will help the player remove the yoke with the same sort of interaction as armbinder.  this involves a diplomacy check, and then the npc will request some 'reward'.  if the player is rude afterwords, the npc will put the yoke back on but keep the key.  this key goes in the npc's inventory and the player can pickpocket the key back if they have enough skill.  or they can kill/get that person killed and take it off their body

Without the key, the npc cant help the player at all.

A blacksmith npc can cut the locks of a yoke for a fee, and if you dont have enough money, he does some other action: (i am undecided here, please weigh in)

1) refuses to do anything (the selfish option)
2) takes all your money and and removes the yoke (the pity option)
3) takes all your money and gives you a belt instead (the revenge option) --- what to do if the player has a belt? just ignore it and move on?
4) takes all your money and gives you a 'quest belt' that can only be removed by the blacksmith when you pay off the rest of the fee (the debt option) --- this is certainly the most labor intensive implementation, and perhaps does not have a place in DDI

**Comment by MinLL** [comment]
4) takes all your money and gives you a 'quest belt' that can only be removed by the blacksmith when you pay off the rest of the fee (the debt option) --- this is certainly the most labor intensive implementation, and perhaps does not have a place in DDI

A fun option, though runs in to the same concerns as "#3" (What if the player is already belted?). Probably better suited as being an optional escape option in Devious Deviants, than in core.

**Comment by Versh** [comment]
Uhm.. Tecnically if we implement the Devious Worker from my mod it could work.. but I think that this take a bit too far...
So: I'm for a simplier solution,

If you don't have enough money you should persuade by Speechcraft (intimidation or persuasion) or offer sex (quickstart), If persuasion succes or the arousal of the Npc is over a Tot (or via configurable probability) he/she accept and you're free
