### ISSUE TITLE
Restrictive collar Features

### ISSUE THREAD

**Issue by LLkoffii** [DeviousDevices/DDi#67]
The collar is similar in construction to the corset. 

Other than simply getting locked, any ideas on further effects and features?

**Comment by Versh** [comment]
Collar restriction proposals:
New Type:
-Bell Collar: Play sound (like footstep) like a Bell, 2 version Cat (soft) and Cow(loud)
Malus: Sneaking (different between Soft and loud)
-I like the idea to Block the head move, but could give some problem also for the free camera or during the SL anim, but it could be done with some work...


Magic Collar: (this could be enchantment to add to the standard collar, so could have one or more)
+Chocking Collar Or Shock collar Category: Can fire an event about a shocking/Chocking, when specific condition are matched depending on the MagicEffect (shocking reduce magicka, Chocking stamina, if goes to 0 drain health)
  -Wizard submission collar: effect when detect magic (Casting, Shouting)
  -Antimagic Collar: Shock if the actor equip a Magic item (the DD still allowed)
  -Fighter Submission Collar: Effect on change of combat state
  -Exposition Collar: Effect if wear Armorcuirass/Armorclothing

I can think about more... for now tell me if I'm going in the right direction...

**Comment by Aelie1** [comment]
add new features for 2.9.1?  keep brainstorming for new ideas.

any kind of camera locking or control is out for gameplay reasons.

**Comment by zenetx** [comment]
jbezorg, on 11 Aug 2014 - 7:51 PM, said:

**Comment by Versh** [comment]
I (and you also, I think) have some problem to make a leash, collar-to-hand-of-master
Personally I was thinking about a "continue cast effect" so we could use the particle system as a leash... but it could do some lag and other issues...

Anyway, collar collar collar...
-Slave Couple collar: tricky but interesting, this force the player to keep the distance from another npc under a certain value or suffering the consequences (depending on the type of collar), The problem is about the assignation of the "Twin"
This could force the player (only) to have a specific follower
I put this on the brainstorm only because could give more ideas to other, but I consider that too much work for nothing

-Reverence collar: this is ispired from SD+, a collar that force the player to get on knees if close to specific npc (male, female, race, eventually animal if enable beastiality on SL)

-Blasphemy/worshipper Collar: close to a shrine of the eight/nine it start some effect (negative or positive) like the arousal animation, if the npc stand in a certain radious from the shrine for too long it start masturbating

-Forbidden Knowlege Collar: It's about haermeus mora... If you read a book you get punished, we could use a variable of the tentacle attch from estrus (dark tentacles) or summon dremora.. I don't know... 
Not suggested: reason -> nothing special/boring, just posted for more ideas

-Guard Collar: It prevents the npc to attack a specific type of Npc (race/sex/faction) so the wearer is exposed to him/her and should flee... Uhm.. I have the suspect to have already posted this...

-Collar of the Unknown trainer: That's interesting but Only for player, is a collar that give to the wearer some specific order (like mental command etc) and  timer to complete the task, this is all about event
Exemple of order:
*Steal something (1 game hour)
*Hit someone (1 game hour)
*Kill someone (12 game hour)
*Get fucked (6 game hour)
*Undress (1 game hour)
*Get arrested (6 game hour)
*Go to a specific location (3 game days)
*Assume some skooma (1 game days)

_____________

All of this are Activation mechanic of the collar... I think that are enough for now... we should focus ourselves on the possible effect
A simple "be fucked" isn't a big deal, we should decide some different scenarios based on a context
for example:
-Humiliation
-Punish (for example a cutscene about the player been exposed in a Zaz anim/cage etc)
-Unknown (an enigmatic message about what you have done when out of control, like an hangover)
-Reward
-Advice
-Humour (Just for example, on DA:O in the pearl with the option "surprise me" you find a male dwarf with tits, 2 nugs, a strange hammer-sexualdevice-wtf inthe room)


Also:
About this variety of activation way, I suggest a little change, Put that activation system in a Magic effect to add to a single Collar type, I think that should be simplier add more and also create custom devices with more effect.
For the other deviced I don't think that is needed, but the collar are the emblematic one

Let me know about all, if need more, if I'm brainstorming in the right direction, etc...
