### ISSUE TITLE
Sort out slot 39 Sexlab conflict (Rollback slot potentially?)

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#97]
http://www.loverslab.com/topic/42177-odd-unequip-issue-during-sexlab-scenes/?p=1056285

**Comment by MinLL** [comment]
Bad news: Slot 39 + http://www.creationkit.com/SetVehicle_-_Actor don't play nicely together.

**Comment by Aelie1** [comment]
is it just 39? does it work fine on other 'vanilla' slots?

**Comment by MinLL** [comment]
(See, this is what I meant when I said "Something will go wrong! :P")

I would guess that it probably happens with the Weapon slots as well, though I haven't tested that. One could easily test this by equipping an item in every vanilla slot, then disabling all stripping settings. Slot 39 is the only slot I've observed this phenomenon on, though it is by no means conclusively only a slot 39 problem. Other vanilla slots (Such as Amulets, gauntlets, boots, etc) work fine.

**Comment by Coopervane** [comment]
Slot-34 (forearms) maybe? As far as i can tell, this is a rarely used slot that's mainly just there to hide clipping issues between forearms and gloves, a few vanilla gauntlets/gloves use it (but those will be hidden/removed by an armbinder anyway as is), and it's almost never used by 3'rd party mods.

However, this is a slightly oddball slot, maybe that's why nobody uses it.. lemme go test this out, see if that's even an option..

**Comment by Coopervane** [comment]
Works just fine. I substituted Slot-39 with Slot-34 in both the AA and Scriptinstance records for the Ebonite Armbinder, it rendered just fine, and it also rendered durring sex.

**Comment by MinLL** [comment]
Resolved by moving the device hider to slot 41.
